name: "Build Plain TeX Live Image"

on:
  push:
    branches:
      - "main"
  schedule:
    - cron: "0 0 * * 0" # 毎週日曜 (UTC)
  workflow_dispatch:

env:
  REGISTRY_IMAGE: ghcr.io/eguchi1611/texlive-sci-ja

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./src
          platforms: linux/amd64,linux/arm64
          push: true
          provenance: false
          tags: ${{ env.REGISTRY_IMAGE }}:plain
