name: "Pre-build TeX Live Dev Container Image"

on:
  push:
    branches:
      - "main"
    paths:
      - "templates/**"
  pull_request:
    branches:
      - "main"
    paths:
      - "templates/**"
  schedule:
    - cron: "0 0 * * 0" # 毎週日曜 (UTC)
  workflow_dispatch:

env:
  REGISTRY_IMAGE: ghcr.io/eguchi1611/texlive-ja

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scheme: [basic, full]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pre-build dev container image
        uses: devcontainers/ci@v0.3
        env:
          BUILDX_NO_DEFAULT_ATTESTATIONS: true
        with:
          imageName: ${{ env.REGISTRY_IMAGE }}
          push: ${{ github.event_name != 'pull_request' && 'always' || 'never' }}
          platform: linux/amd64,linux/arm64
          subFolder: ./src/${{ matrix.scheme }}
          imageTag: ${{ matrix.scheme }}${{ matrix.scheme == 'basic' && ',latest' }}
