name: Pre-build

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0" # 毎週日曜 (UTC)

jobs:
  build:
    # https://github.com/devcontainers/ci/issues/191
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: ASzc/change-string-case-action@v2
        id: repository_name
        with:
          string: ${{ github.repository }}
      - uses: actions/checkout@v4
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ghcr.io/${{ steps.repository_name.outputs.lowercase }}
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha
      - id: format
        # https://github.com/devcontainers/ci/issues/235
        run: |
          prefix="ghcr.io/${{ steps.repository_name.outputs.lowercase }}:"

          tags=$(echo "${{ steps.meta.outputs.tags }}" | sed -e "s#${prefix}##g")
          tags=$(echo "${tags}" | tr "\n" ",")
          tags=$(echo "${tags}" | sed "s/,*$//")

          echo "tags=${tags}" >> $GITHUB_OUTPUT
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: devcontainers/ci@v0.3
        with:
          subFolder: src
          imageName: ghcr.io/${{ steps.repository_name.outputs.lowercase }}
          imageTag: ${{ steps.format.outputs.tags }}
          platform: linux/amd64,linux/arm64
          push: always
          cacheFrom: |
            ghcr.io/${{ steps.repository_name.outputs.lowercase }}
            ghcr.io/${{ steps.repository_name.outputs.lowercase }}:main
